# -*- coding: utf-8 -*-
"""Atividade 6-Aline Melo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQmK-cmFsxzrR0LHmXmKwuO0BFtuQ144

# Atividade - Semana 06 - Trabalhando com dados

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Importe a planilha `dados_starwars.xlsx` na pasta virtual `content`.
"""

# Questao 1
from google.colab import files

# Fazer upload do arquivo
uploaded = files.upload()

import pandas as pd

dados = pd.read_excel("/content/dados_starwars.xlsx")
dados

"""###Questão 2

Remova todos os valores faltantes. Salve a base de dados atualizada.
"""

# Questao 2
dados = dados.dropna()

print(dados.info())
print(dados.head())


dados.to_excel('/content/dados_starwars_sem_nan.xlsx', index=False)

"""###Questão 3

Filtre somente os registros com `especie` = `humano`. Salve a base de dados atualizada.
"""

#Questão 3
import pandas as pd

df = pd.read_excel('dados_starwars.xlsx')

df_humano = df[df['especie'] == 'Humano']

df_humano.to_csv('dados_humanos_atualizados.csv', index=False)

print(df_humano)

"""###Questão 4

Edite a variável `altura` (que esta em centímetros) para que passe para a unidade em metros (*dividir por 100*). Salve a base de dados atualizada.
"""

# Questao 4
import pandas as pd

df = pd.read_excel('dados_starwars.xlsx')

df['altura'] = df['altura'] / 100

df.to_excel('dados_starwars_atualizados.xlsx', index=False)

print(df)

"""###Questão 5

Renomeie a variável `altura` para `altura_metros`. Salve a base de dados atualizada.
"""

# Questao 5
import pandas as pd

dados = pd.read_excel('dados_starwars_atualizados.xlsx')

dados.rename(columns={'altura': 'altura_metros'}, inplace=True)

dados.to_excel('dados_starwars_final.xlsx', index=False)


print(dados.head())

"""###Questão 6

Ordene a base de dados por `altura_metros`. Salve a base de dados atualizada.
"""

# Questao 6
import pandas as pd

dados = pd.read_excel('dados_starwars_final.xlsx')

dados_sorted = dados.sort_values(by='altura_metros')

dados_sorted.to_excel('dados_starwars_ordenados.xlsx', index=False)

print(dados_sorted.head())

"""###Questão 7

Mantenha na base somente as variáveis: `nome`, `altura_metros`, `massa` e `genero`. Salve a base de dados atualizada.



"""

#Questão 7
import pandas as pd

dados = pd.read_excel('dados_starwars_ordenados.xlsx')

df_filtered = dados[['nome', 'altura_metros', 'massa', 'genero']]

df_filtered.to_excel('dados_starwars_final.xlsx', index=False)


print(df_filtered.head())