# -*- coding: utf-8 -*-
"""Atividade_Semana07-Aline Melo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIpgbBfxB6Dz2LKpn5bO7UaVWriZ5guN

# Atividade - Semana 07 - Visualizando Dados

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Crie um gráfico de linha para a expectativa de vida (em anos) da população brasileira:
  -  Adicione um título;
  -  Adicione rótulos nos eixos;
  -  Use o estilo como desejar (cor, marcador, estilo da linha, etc...);
  -  Ao fim, exiba o gráfico usando `plt.show()`.
"""

# Questao 1

from matplotlib import pyplot as plt

anos = [1940, 1950, 1960, 1970, 1980, 1991, 2000, 2010, 2018, 2019, 2020]
expectativa_vida = [45.5, 48, 52.5, 57.6, 62.5, 66.9, 69.8, 73.9, 76.3, 76.6, 76.8]

# Criando o gráfico de linha
plt.figure(figsize=(10, 5))
plt.plot(anos, expectativa_vida, marker='o', linestyle='-', color='green', linewidth=2)

# Adicionando título e rótulos
plt.title('Expectativa de Vida da População Brasileira (1940-2020)')
plt.xlabel('Ano')
plt.ylabel('Expectativa de Vida (anos)')

# Exibindo o gráfico
plt.grid()
plt.show()

"""###Questão 2

Crie um gráfico de barras para o número de temporadas das séries de TV mais longínquas:
  -  Adicione um título;
  -  Adicione rótulos nos eixos;
  -  Use o estilo como desejar (cor, estilo da linha, etc...);
  -  Ao fim, exiba o gráfico usando `plt.show()`.
"""

# Questao 2

series = ["Os Simpsons", "Lei e Ordem: SVU", "Lei e Ordem", "Família da Pesada"]
temporadas = [34, 24, 22, 21]

# Criando o gráfico de barras
plt.figure(figsize=(10, 5))
plt.bar(series, temporadas, color='skyblue')

# Adicionando título e rótulos
plt.title('Número de Temporadas das Séries de TV Mais Longínquas')
plt.xlabel('Séries de TV')
plt.ylabel('Número de Temporadas')

# Exibindo o gráfico
plt.grid(axis='y')
plt.show()

"""###Questão 3

Abaixo temos a altura dos jogadores da seleção brasileira de futebol que participaram da Copa do Mundo 2022. Crie um histograma para a altura destes jogadores.

  -  Adicione um título;
  -  Adicione rótulos nos eixos;
  -  Use o estilo como desejar (cor, estilo da linha, etc...);
  -  Ao fim, exiba o gráfico usando `plt.show()`.
"""

# Questao 3

altura = [1.93, 1.88, 1.88, 1.83, 1.83, 1.83, 1.8, 1.73, 1.85, 1.8, 1.88, 1.85,
          1.8, 1.7, 1.88, 1.83, 1.7, 1.83, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
          1.85, 1.78]

# Criando o histograma
plt.figure(figsize=(10, 5))
plt.hist(altura, bins=10, color='lightcoral', edgecolor='black')

# Adicionando título e rótulos
plt.title('Histograma da Altura dos Jogadores da Seleção Brasileira (Copa do Mundo 2022)')
plt.xlabel('Altura (m)')
plt.ylabel('Número de Jogadores')

# Exibindo o gráfico
plt.grid(axis='y')
plt.show()

"""###Questão 4

Escolha uma das ações disponíveis e crie um gráfico de linha ao longo do tempo:
  -  Adicione um título;
  -  Adicione rótulos nos eixos;
  -  Use o estilo como desejar (cor, estilo da linha, etc...);
  -  Ao fim, exiba o gráfico usando `plt.show()`.
"""

# Questao 4

!pip install yfinance

import yfinance as yf

# OPCOES:
# B3SA3.SA: B3 S.A. - Brasil, Bolsa, Balcão
# BBAS3.SA: Banco do Brasil S.A.
# EMBR3.SA: Centrais Elétricas Brasileiras S.A. - Eletrobrás
# EMBR3.SA: Embraer S.A.
# PETR4.SA: Petróleo Brasileiro S.A. - Petrobras
acoes = yf.download("DIGITE O CODIGO AQUI",  # Por exemplo: "B3SA3.SA"
                    start = "AAAA-MM-DD",    # Por exemplo: 2022-12-01
                    end = "AAAA-MM-DD")      # Por exemplo: 2023-03-18

# separando somente os valores de fechamento
acoes = acoes.loc[:, "Close"]

# renomeando
acoes.index.name = 'data'

import yfinance as yf
import matplotlib.pyplot as plt

# Escolha a ação e o período
acao = "PETR4.SA"  # Exemplo: Petrobras
start_date = "2022-12-01"  # Data de início
end_date = "2023-03-18"     # Data de fim

# Baixando os dados da ação
acoes = yf.download(acao, start=start_date, end=end_date)

# Verificando se os dados foram baixados
if not acoes.empty:
    # Separando somente os valores de fechamento
    fechamento = acoes['Close']

    # Renomeando o índice
    fechamento.index.name = 'Data'

    # Criando o gráfico de linha
    plt.figure(figsize=(10, 5))
    plt.plot(fechamento.index, fechamento, marker='o', linestyle='-', color='blue', linewidth=2)

    # Adicionando título e rótulos
    plt.title(f'Preço de Fechamento da Ação {acao} de {start_date} a {end_date}')
    plt.xlabel('Data')
    plt.ylabel('Preço de Fechamento (R$)')

    # Exibindo o gráfico
    plt.grid()
    plt.xticks(rotation=45)  # Rotaciona as datas para melhor visualização
    plt.show()
else:
    print("Nenhum dado encontrado para a ação ou período especificado.")