# -*- coding: utf-8 -*-
"""Atividade Semana 5-Aline Melo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GL9hwpDyx47ZQ9gLyS3z77cXM3b_5ypU

# Atividade - Semana 05 - Obtendo dados

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Importe a planilha `dados_credito.csv` na pasta virtual `content`.
"""

# Questao 1
import pandas as pd

dados = pd.read_csv("/content/dados_credito.csv")
dados

"""###Questão 2

Instale o pacote `ibge` utilizando `pip`.

(use `!` antes do `pip`)
"""

# Questao 2

!pip install ibge

"""###Questão 3

Similar ao feito no *script da semana 05*, busque informações sobre Estados diretamente do IBGE utilizando a função `Estados()`.

(Não esqueça de importar o pacote corretamente)

(Troque o comando `Municipios()` por `Estados()` utilizando o script da semana 05)
"""

# Questao 3
from ibge.localidades import *

est = Estados()
df_est = pd.json_normalize(est.json())
df_est

"""###Questão 4

Instale o pacote `sgs` utilizando `pip`.

(use `!` antes do `pip`)
"""

# Questao 4

!pip install sgs

"""###Questão 5

Similar ao feito no *script da semana 05*, busque informações no sistema `sgs` sobre o _salário mínimo histórico_ **de 01/01/1990 a 01/03/2023** (código da série: 1619)

(Não esqueça de importar o pacote corretamente)
"""

# Questao 5
# Importando o pacote necessário
import sgs

# Buscando informações sobre o salário mínimo histórico
df_salario = sgs.dataframe(1619, start='01/01/1990', end='01/03/2023')

# Exibindo os dados
print(df_salario)

"""###Questão 6

Instale o pacote `ipeadatapy` utilizando `pip`.

(use `!` antes do `pip`)
"""

# Questao 6
!pip install ipeadatapy

"""###Questão 7

Similar ao feito no *script da semana 05*, busque informações na base `ipeadata` sobre a _produção de café no Brasil em toneladas_ (código da série: `LSPA_QCAFE`)

(Não esqueça de importar o pacote corretamente)
"""

# Questao 7
import ipeadatapy

# o codigo da serie de salario minimo na base
# e 'GAC12_SALMINRE12'
df_cafe = ipeadatapy.timeseries('LSPA_QCAFE')
df_cafe